services:
  redis:
    image: docker.io/library/redis:7.4
    # restarts are managed by systemd
    restart: "no"
    userns_mode: keep-id
    volumes:
      - ./data:/data
    # Do a snapshot of the data every 60s
    command: "redis-server --save 60 1 --loglevel warning"
    networks:
      - systemd-authelia_redis
networks:
  systemd-authelia_redis:
    external: true
