route:
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - send_resolved: true
        to: '$AM_EMAIL'
        from: '$AM_EMAIL'
        smarthost: 'smtp.fastmail.com:587'
        auth_username: '$AM_USERNAME'
        auth_password: '$AM_PASSWORD'
