route:
  routes:
    - matchers:
        - 'severity = none'
      receiver: 'do_nothing'
    - receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - send_resolved: true
        to: '$AM_EMAIL'
        from: '$AM_EMAIL'
        smarthost: 'smtp.fastmail.com:587'
        auth_username: '$AM_USERNAME'
        auth_password: '$AM_PASSWORD'
  - name: 'do_nothing'

inhibit_rules:
  - source_matchers:
      - 'alertname = BackupPeriod'
    target_matchers:
      # TODO: the HostFilesystemDeviceError alert should not be silenced
      - 'alertname =~ "HostFilesystemDeviceError|HostCpuHighIowait|HostUnusualDiskWriteLatency|HostContextSwitchingHigh"'