route:
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - send_resolved: true
        to: '$AM_EMAIL'
        from: '$AM_EMAIL'
        smtp_smarthost: '$AM_ADDRESS'
        smtp_auth_username: '$AM_USERNAME'
        smtp_auth_password: '$AM_PASSWORD'
