global:
  scrape_interval: '15s'
  evaluation_interval: '1m'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'node'
    static_configs:
      - targets: [ 'host.containers.internal:9100' ]
  - job_name: 'alertmanager'
    static_configs:
      - targets: [ 'alertmanager:9093' ]

rule_files:
  - '/etc/prometheus/alerts-*.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: [ 'alertmanager:9093' ]